Repository usermaven/usermaven-js, pull requests merged in 2024-09, with the labels that each got.

#89 change actions path
  .github/workflows/cd-develop.yml
  .github/workflows/cd-master.yml
  .github/workflows/ci.yml
  .github/workflows/master-release.yml
Labels: enhancement

#90 CICD: adding yarn typescript
  .github/workflows/cd-develop.yml
  .github/workflows/cd-master.yml
Labels: enhancement, configuration changes

#92 CICD: bugfix in docker file
  packages/javascript-sdk/docker/Dockerfile
Labels: Bug fix

#93 CICD: add typescript in dockerfile
  packages/javascript-sdk/docker/Dockerfile
Labels: enhancement, configuration changes

#94 CICD: bugfixes in kubernetes deployment
  .github/workflows/cd-develop.yml
  .github/workflows/cd-master.yml
Labels: configuration changes, Bug fix

#95 fix: use beacon api check removed
  packages/javascript-sdk/src/usermaven.ts
Labels: Bug fix
